# UniPlus - SonarQube Configuration
sonar.projectKey=everto18_uniplus_impacta
sonar.organization=everto18

# Sources
sonar.sources=docker/portal-aluno/src,docker/portal-professor/src,docker/sistema-academico/src,docker/video-api/src,lambda/video-processor
sonar.tests=docker/portal-aluno/src/unit_tests,docker/portal-professor/src/unit_tests,docker/sistema-academico/src/unit_tests,docker/video-api/src/unit_tests,tests

# Exclusions
sonar.exclusions=**/node_modules/**,**/vendor/**,**/*.min.js,**/*.min.css,**/assets/img/**,**/assets/fonts/**,.terraform/**,**/*.tfstate*

# Language-specific settings
sonar.python.version=3.12
sonar.php.version=8.3

# Encoding
sonar.sourceEncoding=UTF-8
